### ISSUE TITLE
Automatically build documentation as artifact

### ISSUE THREAD

**Issue by Tjalle-S** [PolarExpress/graphpolaris-vis-api#7]

**Comment by stickyPiston** [comment]
I've been contemplating whether this is actually useful; after the end of project this repo will most likely be on GitLab and having a CI pipeline building the docs will either need to be rewritten or will be deleted in favour of GraphPolaris' deployment_script.

**Comment by peppidesu** [comment]
this issue can be moved to [addon-api-docs](https://github.com/PolarExpress/addon-api-docs) as it is now responsible for building the docs website
